### ISSUE TITLE
error after composer require in backend

### ISSUE THREAD

**Issue by JustMe69** [dachcom-digital/pimcore-toolbox#136]
| Bug report?      | yes
| Feature request? | no

Hi,
I'm using pimcore 6.2.1 and coreshop

When adding composer require dachcom-digital/toolbox:^3.2
all is fine, installation works.

When entering pimcore backend again, following error appears and I have to remove toolbox again to work with pimcore:
```
Areabrick image is already registered as service ToolboxBundle\Document\Areabrick\Image\Image (trying to add service app.area.brick.image)

Es ist eine Ausnahme aufgetreten - der Vorgang konnte nicht durchgeführt werden. Bitte laden Sie die Adminoberfläche neu und versuchen Sie es danach erneut.



Timestamp: Fri Mar 13 2020 09:44:22 GMT+0100 (Mitteleuropäische Normalzeit)
Status: 500 | Internal Server Error
URL: /admin/notification/find-last-unread?interval=30
Message: Areabrick image is already registered as service ToolboxBundle\Document\Areabrick\Image\Image (trying to add service app.area.brick.image)
Trace: 
#0 /var/sq_pimcore/pimcore/var/cache/dev/ContainerUFnEqYH/appAppKernelDevDebugContainer.php(8539): Pimcore\Extension\Document\Areabrick\AreabrickManager->registerService('image', 'app.area.brick....')
#1 /var/sq_pimcore/pimcore/var/cache/dev/ContainerUFnEqYH/appAppKernelDevDebugContainer.php(7895): ContainerUFnEqYH\appAppKernelDevDebugContainer->getAreabrickManagerService()
#2 /var/sq_pimcore/pimcore/var/cache/dev/ContainerUFnEqYH/getPimcore_Templating_Engine_TwigService.php(9): ContainerUFnEqYH\appAppKernelDevDebugContainer->getTwigService()
#3 /var/sq_pimcore/pimcore/var/cache/dev/ContainerUFnEqYH/appAppKernelDevDebugContainer.php(2040): require('/var/sq_pimcore...')
#4 /var/sq_pimcore/pimcore/var/cache/dev/ContainerUFnEqYH/getTemplatingService.php(14): ContainerUFnEqYH\appAppKernelDevDebugContainer->load('getPimcore_Temp...')
#5 /var/sq_pimcore/pimcore/var/cache/dev/ContainerUFnEqYH/appAppKernelDevDebugContainer.php(2040): require('/var/sq_pimcore...')
#6 /var/sq_pimcore/pimcore/var/cache/dev/ContainerUFnEqYH/appAppKernelDevDebugContainer.php(8701): ContainerUFnEqYH\appAppKernelDevDebugContainer->load('getTemplatingSe...')
#7 /var/sq_pimcore/pimcore/var/cache/dev/ContainerUFnEqYH/appAppKernelDevDebugContainer.php(6777): ContainerUFnEqYH\appAppKernelDevDebugContainer->getTargetingListenerService()
#8 /var/sq_pimcore/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(275): ContainerUFnEqYH\appAppKernelDevDebugContainer->ContainerUFnEqYH\{closure}()
#9 /var/sq_pimcore/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(90): Symfony\Component\EventDispatcher\EventDispatcher->sortListeners('kernel.request')
#10 /var/sq_pimcore/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php(334): Symfony\Component\EventDispatcher\EventDispatcher->getListeners('kernel.request')
#11 /var/sq_pimcore/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php(162): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->preProcess('kernel.request')
#12 /var/sq_pimcore/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(127): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\RequestEvent), 'kernel.request')
#13 /var/sq_pimcore/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#14 /var/sq_pimcore/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(198): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#15 /var/sq_pimcore/pimcore/web/app.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#16 {main}
```

What can I do to use toolbox?

kind regards
Stefan

**Comment by solverat** [comment]
It's right in front of you: `Areabrick image is already registered as service`. 
So you probably already have an `image` tag and now the toolbox bundle wants to install another one. Just remove your element before enabling the toolbox bundle.

**Comment by JustMe69** [comment]
So it would be a requirement to have no arebricks installed?
like pimcore skeleton package with nothing?
I'm using pimcore basic-twig and coreshop with demo.
So there are already some areabricks installed.

**Comment by solverat** [comment]
Yea, you have several approaches here at one place. If you're using the basic-twig you should go with it. If you want to use the toolbox, you should (and need) build bricks like documented. We don't like the default pimcore approach of creating an dedicated edit.html.twig file for every element - it leads to pure chaos if you're working on a project with more than 5 developers at the same time. Also, the toolbox comes with some nice build-in bricks, theming, column calculator which are standard in almost every project. So yea, register your bricks via toolbox and your good to go.

**Comment by JustMe69** [comment]
Yeah, I ike to use toolbox ;)

The image brick is not added by myself, it's found in src/AppBundle/Document/Areabrick/Image.php so I think it came with pimcore basic-twig
How can I work-around that - without loosing update functionality?

**Comment by JustMe69** [comment]
![grafik](https://user-images.githubusercontent.com/23456403/76608430-df1a9000-6515-11ea-8549-2265e506c095.png)

Theese bricks are available now

I Addd Product teaser Klio-.. by myself. All others are ready to use
